name: review
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  modal_progress_hud: ^0.1.3
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  firebase_storage: "^7.0.0"
  firebase_database: "^6.0.0"
  clipboard: ^0.1.3
  emojis: ^0.9.3
  rating_dialog: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/